#!/bin/bash
#
# Author: Arian A.
# Co-Author: ChatGPT
# Headphone Detection Script Author: Pico(Macadmins Slack)
# Script: NoHeadphonesNoAudio.sh
# Version: 1.1
# Date: June 28, 2023
# Description: A simple shell script that reduces the volume of a Macintosh computer if no headphones are detected.




# Check if wired headphones are plugged in

headphones_connected_wired="$(
  /usr/bin/osascript -l 'JavaScript' -e '
    ObjC.import("objc");
    ObjC.import("AVFoundation");
    $.objc_getClass("AVAudioSession").sharedInstance.currentRoute.outputs.js.map(thisPortDescription => thisPortDescription.portType.js).includes($.AVAudioSessionPortHeadphones.js);
  '
)"

# Check if Bluetooth headphones are connected

headphones_connected_bluetooth="$(
  /usr/sbin/system_profiler SPAudioDataType | grep -A 3 'Headphone Jack\|Bluetooth' | grep -B 3 -m 1 'Headphone Jack\|Bluetooth'
)"

if [ "${headphones_connected_wired}" = 'true' ] || [[ "$headphones_connected_bluetooth" != "" ]]; then
  echo 'Headphones ARE connected, volume untouched'
  echo 'Thanks Pico' 
else
  # Headphones not detected, check and adjust volume
  volume=$(osascript -e 'output volume of (get volume settings)')

  if [[ "$volume" -gt 3 ]]; then
    osascript -e 'set volume output volume 0'
    echo "Volume set to 0."
  else
    echo "Volume is already low."
  fi
fi
